# Generated by Django 4.1.5 on 2023-03-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('tugilgan_yil', models.DateField()),
                ('jins', models.CharField(max_length=10)),
                ('davlat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('narx', models.PositiveIntegerField()),
                ('muddat', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Kino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1000)),
                ('yil', models.DateField()),
                ('janr', models.CharField(max_length=100)),
                ('aktyorlar', models.ManyToManyField(to='asosiy.aktyor')),
            ],
        ),
    ]
