# Generated by Django 4.1.5 on 2023-03-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktyor',
            name='davlat',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
